### ISSUE TITLE
Newer Builds now change the actual resolution of the Screen?

### ISSUE THREAD

**Issue by CaptainCoward** [Kron4ek/Wine-Builds#155]
I'm sorry i know this might not really be an Issue but i don't know where else to ask. I noticed that when using the newer builds now actually change the resolution of my actual screen. Is that intended behaviour? And is there a way to prevent that? I actually liked that before it would just scale the games.

**Comment by Kron4ek** [comment]
This is because the fullscreen hack patch, which allowed to change in-game resolution without changing the actual desktop resolution, is not compatible with new Wine versions.

> And is there a way to prevent that?

Use [gamescope](https://github.com/ValveSoftware/gamescope) or Wine's virtual desktop. Or use wine-proton builds, they support this feature.

**Comment by CaptainCoward** [comment]
Ty that already answers my question :)
