### ISSUE TITLE
Q - How to install your builds to be used instead of default wine?

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Kron4ek/Wine-Builds#2]
I want to use your builds instead of Wine-staging that is installed on Ubuntu. I mean installing not just using any of them.

**Comment by Kron4ek** [comment]
As these builds provided as plain archives and not as packages (like deb or rpm), you can't install them through package manager. 

But you can unpack desired build(s) to /opt and then change PATH environment variable to make system use required build instead of the one installed from repo:

    export PATH="/opt/wine-4.6-staging-amd64/bin:$PATH"
   
You can add this command to ~/.bash_profile and it will performs automatically on system startup.

That's it. Check if desired build is actually used:

    wine --version
     
Or you can specify full path to Wine binary when launch application, changing PATH is not needed in that case.

    /opt/wine-4.6-staging-amd64/bin/wine app.exe

**Comment by ahmed-elsayed2017** [comment]
Ok. Thanks for your replay.
