### ISSUE TITLE
Q - How can I use seccomp with your latest Proton build?

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#20]
The command `proton_use_seccomp=1 %command%` is required by the new Denuvo games, and it works with Proton, but I need to use Steam in order for that to work.

I simply want to use this command with your Proton builds outside of Steam. How can I do that?

**Comment by Kron4ek** [comment]
All the environment variables that contain "PROTON_" string in their name are specific to Steam and work only inside Steam (because they are handled not by Wine itself, but by the ["proton" python script](https://github.com/ValveSoftware/Proton/blob/proton_5.13/proton)).

However, this is usually not a problem, because all (or almost all) these variables are just aliases for other environment variables.

I will list some of them:

`PROTON_USE_WINED3D` is an alias for `WINEDLLOVERRIDES="d3d11,d3d10,d3d10core,d3d10_1,d3d9=b"`
`PROTON_NO_D3D11` is an alias for `WINEDLLOVERRIDES="d3d11="`
`PROTON_FORCE_LARGE_ADDRESS_AWARE` is an alias for `WINE_LARGE_ADDRESS_AWARE=1`
`PROTON_USE_SECCOMP` is an alias for `WINESECCOMP=1`
`PROTON_OLD_GL_STRING` is an alias for `MESA_EXTENSION_MAX_YEAR=2003` and `__GL_ExtensionStringVersion=17700`

So to enable seccomp you have to use WINESECCOMP environment variable:

`export WINESECCOMP=1`

**Comment by Ahmed-E-86** [comment]
Thank you so much. That is really helpful.

**Comment by Ahmed-E-86** [comment]
I am sorry one more question if you don't mind. Is seccomp included with WINE-TKG? Or is it exclusive to Proton only?

**Comment by Kron4ek** [comment]
Yes, it's included in Wine-TkG and in regular Wine-Staging (since 5.0-rc4) and enabled by default.

**Comment by Ahmed-E-86** [comment]
That is great. Thanks again.

**Comment by jiriks74** [comment]
> Yes, it's included in Wine-TkG and in regular Wine-Staging (since 5.0-rc4) and enabled by default. Vanilla Wine still doesn't contain it though.
> 
> [This](https://github.com/wine-staging/wine-staging/blob/master/patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch) is the patch that adds seccomp in Wine-Staging.

I've been trying to find something about seccomp and wine but I couldn't find anything so sorry for asking here. Will I be able to run anticheat software if I use seccomp?

**Comment by Kron4ek** [comment]
> Will I be able to run anticheat software if I use seccomp?

Unfortunately no, kernel-level anticheats don't work under Wine even with seccomp.

**Comment by Ahmed-E-86** [comment]
There is initial support for it from Collobora in the latest kernel. Hopefully it will be supported in the future.

**Comment by jiriks74** [comment]
> Unfortunately no, kernel-level anticheats don't work under Wine even with seccomp.
@Kron4ek 
Why? From the readme it says that when you enable seccomp it translates windows syscalls ti linux syscalls. Why wouldn't anticheat work? - Sorry if I'm annoying, I'm just curious.



> There is initial support for it from Collobora in the latest kernel. Hopefully it will be supported in the future.
@Ahmed-E-86 
Yeah. 5.11 is out with syscall user dispatch. But there isn't any implementation even in proton, where I thought there would be something ready with the kernel since valve is working on both. Anyway, let's hope that at least "beta" will be available in weeks rather than months.

**Comment by Kron4ek** [comment]
@jiriks74 Sorry, i'm not competent enough on this subject to tell you why.

@Ahmed-E-86 According to some sources ([one](https://www.reddit.com/r/linux_gaming/comments/l6cam9/syscall_dispatch_and_kernel_511_clarification/), [two](https://www.reddit.com/r/linux_gaming/comments/jtz08q/collabora_on_twitter_tomorrow_at_1020_utc_on_day/gcad89o/)), syscall dispatch feature in the 5.11 kernel is not about anticheat support.

**Comment by jiriks74** [comment]
> @Ahmed-E-86 According to some sources ([one](https://www.reddit.com/r/linux_gaming/comments/l6cam9/syscall_dispatch_and_kernel_511_clarification/), [two](https://www.reddit.com/r/linux_gaming/comments/jtz08q/collabora_on_twitter_tomorrow_at_1020_utc_on_day/gcad89o/)), syscall dispatch feature in the 5.11 kernel is not about anticheat support.
@Kron4ek 

No, but it allows, from what I understand, set a part of the game, not whole, to send syscalls to user space instead of kernel. This would allow to run anticheat if wine would support translating syscalls with it. The anticheat would make a syscall, syscall user dispatch would send it to wine instead of kernel, wine would translate it and send it to kernel.

**Comment by Ahmed-E-86** [comment]
> No, but it allows, from what I understand, set a part of the game, not whole, to send syscalls to user space instead of kernel. This would allow to run anticheat if wine would support translating syscalls with it. The anticheat would make a syscall, syscall user dispatch would send it to wine instead of kernel, wine would translate it and send it to kernel.

A developer managed to make EAC to run through wine, and it ran in the user space instead of the kernel, but EAC developers patched their anti cheat to block that. The only way for this to work in the long term is from the kernel directly without interference from wine.

**Comment by Kron4ek** [comment]
@jiriks74 
As far as i know, this is exactly what Wine-Staging and Proton already can do with seccomp. This is why games that make direct syscalls (like Detroit Become Human or Red Dead Redemption 2) already work under Wine. According to the first link above and [the description of the syscall user dispatch](https://lkml.org/lkml/2020/11/18/815), seccomp is just slow and not so convenient for this task.

**Comment by jiriks74** [comment]
@Ahmed-E-86 
The thing is that the eac would send it to kernel like it normally would, but the kernel sends it to wine which translates it for linux kernel, sends it to kernel and then the kernel sends response to eac. The eac wouldn't know about this. The only thing is that it would be slower than normal.

This is what I understand from several articles

**Comment by jiriks74** [comment]
I made a discussion, so we wouldn't just spam this [issue](https://github.com/Kron4ek/Wine-Builds/discussions/33)
