### ISSUE TITLE
Broken Controller Support? - Wine-Tkg-Staging 5.20

### ISSUE THREAD

**Issue by Luis-Douet** [Kron4ek/Wine-Builds#23]
Hi Kron4ek,

When using your builds **wine-5.19-staging-tkg-amd64.tar.xz** and **wine-5.20-staging-amd64.tar.xz**,  DualShock 3 & 4 controllers are able to be detected and used in games through Lutris.

When using **wine-5.20-staging-tkg-amd64.tar.xz** DualShock 3 & 4 controllers are not able to be detected or used in games through Lutris.

System
OS: Debian Sid
Desktop Environment: KDE
Kernel: 5.9.0-1

Thank you for the service you provide!

**Comment by Kron4ek** [comment]
Hello. 

The staging's dinput patches are [disabled](https://github.com/Frogging-Family/wine-tkg-git/commit/ab18cc0f97ad84517986358483e767b292a27890#diff-594bde75ad3eab653701097d948540cb11d9a6ac3f3b7b8dd9379bb2198aa123) (if proton-rawinput is enabled) in tkg-5.20 because they conflict with proton-rawinput patch, which is also contains gamepad patches, but not all gamepads work with them (i guess)? Perhaps this is the reason. Also proton-fs-hack and some other patches are not updated yet and not included in tkg-5.20.

You can try [this](https://mega.nz/file/IR8xBIoI#vopHz2EuE5TpYe8dk-UjHEpWxxALXY4RLPiVpCyLAws) build, which i compiled with proton-rawinput patch disabled, so the Staging's dinput patches are included. Please let me know if your controllers work with it.

**Comment by Luis-Douet** [comment]
I guess you are right and there may be a conflict with the new gamepad patches. The build you compiled with "proton-rawinput patch disabled" works great! I tested both DualShock 3 & 4 controllers through a couple of games so feel free to close this issue.

Do you think that this is an issue that should be brought up to Tk-Glitch or just wait until patches restore controller support? I assume there is no easy way to disable these new patches without compiling a new build?

Thank you for the build and information!

**Comment by Kron4ek** [comment]
> The build you compiled with "proton-rawinput patch disabled" works great! I tested both DualShock 3 & 4 controllers through a couple of games so feel free to close this issue.

Good!

> Do you think that this is an issue that should be brought up to Tk-Glitch or just wait until patches restore controller support?

Yes, considering that the issue is in the proton-rawinput-nofshack patch, i think it makes sense to report this issue to Tk-Glitch. But i also think that it's better to wait at least for proton-fs-hack patch update (which will also lead to proton-rawinput patch update), and then we will see.

> I assume there is no easy way to disable these new patches without compiling a new build?

Right, these patches can be enabled/disabled only by recompilation.
